---
- name: APT update
  ansible.builtin.apt:
    update_cache: true

- name: copy some test files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  loop:
    - helloWorld/helloWorld.py
    - helloWorld/helloWorld.sh
