---
# hello_playbook.yml
---
# hello_playbook.yml
- hosts: tag_Name_Ops_Sysops
  become: true
  gather_facts: yes

  pre_tasks:
    - include_tasks: helloWorld/helloWorld_preTasks.yml

  post_tasks:
    - include_tasks: helloWorld/helloWorld_postTasks.yml
