name: Run Ansible Playbook 'hello world'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ansible:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ansible Playbook
        run: ansible-playbook -i ./ansible/hosts ./ansible/hello_playbook.yml -vvvv --limit=operations3.access-ci.org
